var config = {
    stationName: {
        "15":{"name":"蝴蝶Butterfly","zone":"1"},
        "260":{"name":"豐景園Goodview Garden","zone":"1"},
        "20":{"name":"輕鐵車廠Light Rail Depot","zone":"1"},
        "30":{"name":"龍門Lung Mun","zone":"1"},
        "10":{"name":"美樂Melody Garden","zone":"1"},
        "920":{"name":"三聖Sam Shing","zone":"1"},
        "240":{"name":"兆禧Siu Hei","zone":"1"},
        "265":{"name":"兆麟Siu Lun","zone":"1"},
        "1":{"name":"屯門碼頭Tuen Mun Ferry Pier","zone":"1"},
        "250":{"name":"屯門泳池Tuen Mun Swimming Pool","zone":"1"},
        "80":{"name":"澤豐Affluence","zone":"2"},
        "75":{"name":"蔡意橋Choy Yee Bridge","zone":"2"},
        "70":{"name":"河田Ho Tin","zone":"2"},
        "310":{"name":"何福堂Hoh Fuk Tong","zone":"2"},
        "60":{"name":"建安Kin On","zone":"2"},
        "200":{"name":"鳴琴Ming Kum","zone":"2"},
        "230":{"name":"銀圍Ngan Wai","zone":"2"},
        "270":{"name":"安定On Ting","zone":"2"},
        "330":{"name":"景峰Prime View","zone":"2"},
        "300":{"name":"杯渡Pui To","zone":"2"},
        "320":{"name":"新墟San Hui","zone":"2"},
        "180":{"name":"山景（北）Shan King (North)","zone":"2"},
        "190":{"name":"山景（南）Shan King (South)","zone":"2"},
        "170":{"name":"石排Shek Pai","zone":"2"},
        "212":{"name":"大興（北）Tai Hing (North)","zone":"2"},
        "220":{"name":"大興（南）Tai Hing (South)","zone":"2"},
        "280":{"name":"市中心Town Centre","zone":"2"},
        "40":{"name":"青山村Tsing Shan Tsuen","zone":"2"},
        "50":{"name":"青雲Tsing Wun","zone":"2"},
        "295":{"name":"屯門Tuen Mun","zone":"2"},
        "275":{"name":"友愛Yau Oi","zone":"2"},
        "120":{"name":"青松Ching Chung","zone":"3"},
        "370":{"name":"鍾屋村Chung Uk Tsuen","zone":"3"},
        "340":{"name":"鳳地Fung Tei","zone":"3"},
        "110":{"name":"麒麟Kei Lun","zone":"3"},
        "130":{"name":"建生Kin Sang","zone":"3"},
        "350":{"name":"藍地Lam Tei","zone":"3"},
        "150":{"name":"良景Leung King","zone":"3"},
        "360":{"name":"泥圍Nai Wai","zone":"3"},
        "160":{"name":"新圍San Wai","zone":"3"},
        "100":{"name":"兆康Siu Hong","zone":"3"},
        "140":{"name":"田景Tin King","zone":"3"},
        "90":{"name":"屯門醫院Tuen Mun Hospital","zone":"3"},
        "490":{"name":"翠湖Chestwood","zone":"4"},
        "455":{"name":"銀座Ginza","zone":"4"},
        "425":{"name":"坑尾村Hang Mei Tsuen","zone":"4"},
        "380":{"name":"洪水橋Hung Shui Kiu","zone":"4"},
        "448":{"name":"樂湖Locwood","zone":"4"},
        "400":{"name":"屏山Ping Shan","zone":"4"},
        "460":{"name":"天瑞Tin Shui","zone":"4"},
        "430":{"name":"天水圍Tin Shui Wai","zone":"4"},
        "435":{"name":"天慈Tin Tsz","zone":"4"},
        "500":{"name":"天榮Tin Wing","zone":"4"},
        "450":{"name":"天湖Tin Wu","zone":"4"},
        "445":{"name":"天耀Tin Yiu","zone":"4"},
        "390":{"name":"塘坊村Tong Fong Tsuen","zone":"4"},
        "570":{"name":"豐年路Fung Nin Road","zone":"5"},
        "580":{"name":"康樂路Hong Lok Road","zone":"5"},
        "560":{"name":"水邊圍Shui Pin Wai","zone":"5"},
        "590":{"name":"大棠路Tai Tong Road","zone":"5"},
        "600":{"name":"元朗Yuen Long","zone":"5"},
        "468":{"name":"頌富Chung Fu","zone":"5A"},
        "480":{"name":"天富Tin Fu","zone":"5A"},
        "540":{"name":"天恆Tin Heng","zone":"5A"},
        "520":{"name":"天秀Tin Sau","zone":"5A"},
        "550":{"name":"天逸Tin Yat","zone":"5A"},
        "510":{"name":"天悅Tin Yuet","zone":"5A"},
        "530":{"name":"濕地公園Wetland Park","zone":"5A"},
        "385":{"name":"洪天路緊急月台Hung Tin Road Emergency Platform","zone":"緊急月台"}
    }, etaURL: "https://rt.data.gov.hk/v1/transport/mtr/lrt/getSchedule"
};

export default config;